name: Run Config Collector # نام Workflow اصلی

on:
  workflow_dispatch: # اجازه اجرای دستی را می‌دهد (برای Job اصلی و ریست)
  # schedule: # زمان‌بندی اجرای خودکار (همچنان غیرفعال)
  #   - cron: '0 */6 * * *'
  #     env:
  #       TZ: Asia/Tehran

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # برای Push کردن تغییرات لازم است

    env:
      TZ: Asia/Tehran

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # یا نسخه پایتون مورد نظر شما

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create output directories
        run: |
          mkdir -p output/subs/plaintext/protocols
          mkdir -p output/subs/base64/protocols
          mkdir -p output/ # برای report.md و timeout files

      - name: Run the Config Collector
        run: |
          export PYTHONPATH=$PWD:$PYTHONPATH
          python main.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Add and Commit changes
        run: |
          git add output/subs/
          git add output/report.md
          git add output/timeout_telegram_channels.json # اینها برای حفظ وضعیت push میشوند
          git add output/timeout_websites.json          # اینها برای حفظ وضعیت push میشوند
          
          git commit -m "Auto: Update collected configs, report, and timeout stats" || echo "No changes to commit"
          git push

  # NEW JOB: Reset Statistics and Timeouts
  # JOB جدید: ریست کردن آمار و لیست‌های تایم‌اوت
  reset-stats-and-timeouts:
    runs-on: ubuntu-latest
    permissions:
      contents: write # برای Push کردن تغییرات لازم است

    on:
      workflow_dispatch: # فقط با اجرای دستی قابل فعال‌سازی است
        inputs:
          confirm_reset:
            description: 'Are you sure you want to reset all stats and timeouts? Type "yes" to confirm.'
            required: true
            type: string
            default: 'no'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Confirmation # بررسی تایید کاربر قبل از ریست
        run: |
          if [ "${{ github.event.inputs.confirm_reset }}" != "yes" ]; then
            echo "Reset not confirmed. Exiting without changes."
            exit 1
          fi
          echo "Reset confirmed. Proceeding with reset."

      - name: Reset Statistics and Timeouts # حذف فایل‌های آمار و تایم‌اوت
        run: |
          echo "Deleting timeout and report files..."
          rm -f output/timeout_telegram_channels.json
          rm -f output/timeout_websites.json
          rm -f output/report.md
          
          # می‌توانید فایل collected_links.json را هم پاک کنید اگر نمی‌خواهید نگه داشته شود
          # rm -f output/collected_links.json 
          
          echo "Files deleted."

      - name: Configure Git # پیکربندی Git برای Commit و Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Commit and Push Reset # کامیت و Push کردن تغییرات ریست
        run: |
          git add output/timeout_telegram_channels.json # اضافه کردن فایل های حذف شده (برای ثبت حذف)
          git add output/timeout_websites.json
          git add output/report.md
          # git add output/collected_links.json # اگر بالا پاک کردید، اینجا هم اضافه کنید
          
          git commit -m "Auto: Reset collection statistics and timeouts" || echo "No changes to commit (files might not have existed)"
          git push
        env:
          # از GITHUB_TOKEN برای احراز هویت استفاده می‌کند
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

