name: Run Config Collector # نام Workflow که در GitHub UI نمایش داده می‌شود

on:
  workflow_dispatch: # رویداد: اجازه اجرای دستی از رابط کاربری GitHub را می‌دهد
  # schedule: # رویداد: زمان‌بندی اجرای خودکار (در حال حاضر کامنت شده و غیرفعال است)
  #   - cron: '0 */6 * * *' # هر 6 ساعت یک بار اجرا می‌شود (در دقیقه 0 بعد از هر 6 ساعت)
  #     # مثال: 00:00, 06:00, 12:00, 18:00 (به وقت UTC)
  #     # برای فعال‌سازی، کاراکتر '#' را از ابتدای 'schedule:' و خط پایین آن حذف کنید.

jobs:
  build-and-run:
    runs-on: ubuntu-latest # استفاده از آخرین رانر اوبونتو برای اجرای Job
    
    permissions:
      contents: write # اعطای دسترسی نوشتن به GITHUB_TOKEN برای Push کردن تغییرات

    env:
      TZ: Asia/Tehran # تنظیم منطقه زمانی برای Job، که بر زمان‌بندی cron و timestamp های اسکریپت تأثیر می‌گذارد

    steps:
      - name: Checkout repository # دریافت کد شما از مخزن GitHub
        uses: actions/checkout@v4

      - name: Set up Python # تنظیم محیط پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # یا '3.10', '3.11', '3.12' - نسخه پایتون مورد نظر خود را انتخاب کنید
          # توصیه می‌شود از نسخه‌های جدیدتر پایتون مانند '3.11' یا '3.12' استفاده کنید.

      - name: Install dependencies # نصب کتابخانه‌های پایتون از requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create output directories # اطمینان از وجود تمام پوشه‌های خروجی لازم
        # این مرحله صرفاً برای ایجاد پوشه‌ها قبل از اجرای اسکریپت اصلی است.
        # OutputManager در پایتون نیز این پوشه‌ها را ایجاد می‌کند.
        run: |
          mkdir -p output/subs/base64
          mkdir -p output/subs/plaintext
          mkdir -p output/subs/mixed
          mkdir -p output/subs/protocols # ایجاد پوشه جدید برای پروتکل‌های جداگانه
          mkdir -p output/ # اطمینان از وجود پوشه output برای report.md و timeout files

      - name: Run the Config Collector # اجرای اسکریپت اصلی پایتون شما
        # افزودن دایرکتوری فعلی به PYTHONPATH برای یافتن ماژول‌ها
        run: |
          export PYTHONPATH=$PWD:$PYTHONPATH # Add current working directory to Python path
          python main.py # Execute the main script

      # NEW: Add steps to commit and push changes to the repository
      - name: Configure Git # پیکربندی Git با نام کاربری و ایمیل (نام عمومی)
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Add and Commit changes # اضافه کردن، کامیت کردن و Push کردن فایل‌های تولید شده
        run: |
          # اضافه کردن کل پوشه 'subs' که شامل تمامی خروجی‌های کانفیگ است.
          git add output/subs/
          # اضافه کردن فایل گزارش Markdown
          git add output/report.md
          
          # اگر فایل‌های timeout (JSON) را نیز می‌خواهید Push کنید (برای مشاهده وضعیت امتیازات):
          git add output/timeout_telegram_channels.json
          git add output/timeout_websites.json
          
          # ایجاد یک commit؛ اگر تغییری نباشد، پیام "No changes to commit" را چاپ می‌کند و Job را با موفقیت ادامه می‌دهد.
          git commit -m "Auto: Update collected configs and report" || echo "No changes to commit"
          git push
