name: Reset Collection Data # نام این Workflow در GitHub UI

on:
  workflow_dispatch: # رویداد: اجازه اجرای دستی از رابط کاربری GitHub را می‌دهد
    inputs:
      confirm_reset:
        description: 'آیا از ریست کردن تمام آمار و تایم‌اوت‌ها مطمئن هستید؟ برای تایید "بله" را تایپ کنید.'
        required: true
        type: string
        default: 'خیر' # 'no' in Farsi

jobs:
  reset-stats-and-timeouts:
    runs-on: ubuntu-latest
    permissions:
      contents: write # برای Push کردن تغییرات لازم است

    steps:
      - name: Checkout repository # دریافت کد شما از مخزن GitHub
        uses: actions/checkout@v4

      - name: Check Confirmation # بررسی تایید کاربر قبل از ریست
        run: |
          if [ "${{ github.event.inputs.confirm_reset }}" != "بله" ]; then
            echo "Reset confirmed: '${{ github.event.inputs.confirm_reset }}'"
            echo "ریست تایید نشد. بدون تغییرات خارج می‌شود."
            exit 1
          fi
          echo "ریست تایید شد. ادامه عملیات ریست."

      - name: Reset Statistics and Timeouts # حذف فایل‌های آمار و تایم‌اوت
        run: |
          echo "حذف فایل‌های گزارش و تایم‌اوت..."
          # از 'git rm -f' برای حذف فایل‌هایی که ممکن است قبلاً به Git اضافه شده باشند استفاده می‌کنیم.
          # '|| true' اضافه شده تا اگر فایل وجود نداشت، دستور با خطا مواجه نشود و ادامه یابد.
          git rm -f output/timeout_telegram_channels.json || true
          git rm -f output/timeout_websites.json || true
          git rm -f output/report.md || true
          # اگر collected_links.json را هم می‌خواهید پاک کنید:
          # git rm -f output/collected_links.json || true
          echo "فایل‌ها حذف شدند."

      - name: Configure Git # پیکربندی Git برای Commit و Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Commit and Push Reset # کامیت و Push کردن تغییرات ریست
        run: |
          # 'git add -u' همه فایل‌های ردیابی شده که حذف شده‌اند را به مرحله آماده‌سازی اضافه می‌کند.
          # این اطمینان می‌دهد که حتی اگر فایل‌ها قبلا توسط 'rm -f' حذف شده باشند، حذف آن‌ها ثبت شود.
          git add -u output/ # اضافه کردن تمامی تغییرات (از جمله حذف فایل‌ها) در پوشه output
          
          git commit -m "Auto: Reset collection statistics and timeouts" || echo "No changes to commit (files might not have existed or were already removed)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
