name: Reset Collection State # نام این Workflow در GitHub UI (تغییر کرد)

on:
  workflow_dispatch: # رویداد: اجازه اجرای دستی از رابط کاربری GitHub را می‌دهد
    inputs:
      confirm_reset:
        description: 'آیا از ریست کردن آمار جمع‌آوری، تایم‌اوت‌ها و منابع کشف‌شده مطمئن هستید؟ (منابع اصلی دست‌نخورده می‌مانند). برای تایید "بله" را تایپ کنید.'
        required: true
        type: string
        default: 'خیر' # 'no' in Farsi

jobs:
  reset-state-only: # نام Job تغییر کرد (فقط ریست وضعیت)
    runs-on: ubuntu-latest
    permissions:
      contents: write # برای Push کردن تغییرات لازم است

    steps:
      - name: Checkout repository # دریافت کد شما از مخزن GitHub
        uses: actions/checkout@v4

      - name: Check Confirmation # بررسی تایید کاربر قبل از ریست
        run: |
          if [ "${{ github.event.inputs.confirm_reset }}" != "بله" ]; then
            echo "Reset confirmed: '${{ github.event.inputs.confirm_reset }}'"
            echo "ریست تایید نشد. بدون تغییرات خارج می‌شود."
            exit 1
          fi
          echo "ریست وضعیت تایید شد. ادامه عملیات."

      - name: Reset Collection State Files # حذف فایل‌های وضعیت جمع‌آوری
        run: |
          echo "حذف فایل‌های گزارش، تایم‌اوت و لیست‌های منابع کشف‌شده..."
          
          # 1. حذف فایل‌های تایم‌اوت
          git rm -f output/timeout_telegram_channels.json || true
          git rm -f output/timeout_websites.json || true
          
          # 2. حذف فایل گزارش
          git rm -f output/report.md || true
          
          # 3. حذف لیست لینک‌های جمع‌آوری شده (اختیاری، اما برای شروع کاملاً تازه مفید است)
          git rm -f output/collected_links.json || true
          
          # 4. حذف فایل‌های منابع کشف‌شده (این‌ها باید پاک بشن تا برنامه دوباره کشف کنه)
          git rm -f sources/discovered_telegram_channels.txt || true
          git rm -f sources/discovered_websites.txt || true

          echo "فایل‌های وضعیت جمع‌آوری حذف شدند. منابع اصلی (channels.txt و websites.txt) دست‌نخورده باقی ماندند."

      - name: Configure Git # پیکربندی Git برای Commit و Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: Commit and Push Reset # کامیت و Push کردن تغییرات ریست
        run: |
          # 'git add -u .' همه فایل‌های ردیابی شده که حذف شده‌اند را به مرحله آماده‌سازی اضافه می‌کند.
          git add -u . 

          git commit -m "Auto: Reset collection state (timeouts, reports, discovered sources only)" || echo "No changes to commit (files might not have existed or were already removed)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}